### ISSUE TITLE
How to get data about games for particular date?

### ISSUE THREAD

**Issue by Gradoma** [peruukki/nhl-score-api#5]
Is it possible to make GET request for particular date, not only for "latest"? I can't find such option in readme.

**Comment by peruukki** [comment]
Unfortunately not, you can only get the latest games. But I've also been thinking about adding the possibility to request games within a date range since the NHL API supports that, just haven't gotten around to doing it because I haven't had the need. It shouldn't be too much work though, so I can look into it in coming weeks. 🙂

**Comment by peruukki** [comment]
Now there is an [endpoint for a date range request](https://github.com/peruukki/nhl-score-api#get-apiscoresstartdateyyyy-mm-ddenddateyyyy-mm-dd). It took longer than I expected, mostly due to my modest Clojure skills (I created this project partly as a way to improve them) and the fact that the service has been so simple until this, without external parameter handling.

Let me know if you find some problems with it, or just have questions. 🙂
