### ISSUE TITLE
The server is down

### ISSUE THREAD

**Issue by guillaume-infernal** [peruukki/nhl-score-api#8]
Hi,

The server is currently returning a [500 error](https://nhl-score-api.herokuapp.com/api/scores/latest)

Thanks for your help

**Comment by peruukki** [comment]
Hi, thanks for reporting! Turns out the NHL site has switched to a new API and they have shut down the previous one at https://statsapi.web.nhl.com that this project uses. There's a [related discussion](https://gitlab.com/dword4/nhlapi/-/issues/110) where some kind people have documented their findings about the new API, apparently statsapi already went down once in September but came back soon. In any case I'll need to switch to the new API, but not sure yet how long it will take.

**Comment by ChrisArchitect** [comment]
Ahh! Thanks for the update. That discussion with what's known so far is interesting too. Your efforts are appreciated!

**Comment by peruukki** [comment]
In case you missed it, the API should be working now at least for this season's games. I still need to add playoff related stats if playoff games are requested, but let me know if something else is not working.

**Comment by ChrisArchitect** [comment]
I don't know if I'm seeing this right, but during LIVE games, right near the end of the 3rd period (haven't looked at the end of other periods), when <5 mins, all of a sudden the /latest endpoint reports the games as back in "PREVIEW" state? Have seen multiple games since yesterday do this.
Is there a new game state called "CRITICAL"? Not sure what that means. But /latest reports no active game at that point, no score etc.
Anything can be done? Appreciate the efforts

**Comment by peruukki** [comment]
Thanks for reporting! I was aware of the "critical" game state but had no idea what it meant. I guessed it was for some critical situation at the arena or something that would postpone or delay the game, but looks like it was less severe than that. 😄 I made a quick fix to treat it as "LIVE".

**Comment by ChrisArchitect** [comment]
Thanks for that. I'm sorry I might have mislead - the state seems to change back to PREVIEW in the later minutes..... not actually CRITICAL, but I was speculating that also meant something. It's just weird that the games disappear from the feed when they're still live. 
Will see what happens in upcoming games! thanks!

**Comment by peruukki** [comment]
No worries, I think I got what you meant. As background, the new NHL API has more game states than the previous one ("critical" being one of the new ones) but I wanted to keep the output of my API unchanged, so I now map the NHL API's 8 different states (if you count postponed games too, which are reported a bit differently and I haven't added handling for them yet) into the 4 ones that my API returns. And now "critical" is mapped to "LIVE" instead of "PREVIEW".

**Comment by ChrisArchitect** [comment]
ah ha. Yeah, on latest it seems to be working now. Nice one!

**Comment by peruukki** [comment]
I finished the migration to the new API, so I'll close this issue. But feel free to open new issues if you see something weird. 🙏
